- name: create group
  group:
    name: "{{ username }}"
    state: present

- name: create user
  user:
    name: "{{ username }}"
    group: "{{ username }}"
    shell: /bin/bash
    uid: 1001

- name: create folder for .ssh
  file:
      path: /home/{{ username }}/.ssh
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0700
