---


- name: Update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: apt-upgrade


- name: Upgrade all packages if required
  apt:
    upgrade: dist
  tags: [ 'never', 'apt-upgrade' ]


- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  tags: [ 'never', 'apt-upgrade' ]


- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags: [ 'never', 'apt-upgrade' ]
