- name: install apache and php (redhat based distro)
  ansible.builtin.dnf:
    name: "{{ service_rh }}"
    state: latest
  when: ansible_distribution in ["Centos", "Rocky"]


- name: install apache and php (debian based distro)
  ansible.builtin.apt:
    name: "{{ service_deb }}"
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]