- name: Download agent files
  get_url:
    url: http://192.168.0.85:8111/update/buildAgent.zip
    dest: /{{username}}/{{application}}/content/

- name: unzip teamcity files
  unarchive:
    src: /{{username}}/{{application}}/content/buildAgent.zip
    dest: /{{username}}/{{application}}/data
    owner: "{{ username }}"
    group: "{{ username }}"
    remote_src: yes

- name: delete zip file
  file:
      path: /{{username}}/{{application}}/content/buildAgent.zip
      state: absent
