- name: Install packages and role dependencies1
  apt:
    name: mc,nmon
    state: "present"
    install_recommends: False
    update_cache: True
    cache_valid_time: 86400


- name: Install packages and role dependencies2
  apt:
    name: "{{ item }}"
    state: "present"
    install_recommends: False
    update_cache: True
    cache_valid_time: 86400
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "cron"
    - "supervisor"
    - "unzip"
    - "wget"
    - "openjdk-8-jdk"
    - "htop"




- name: set timezone to UTC
  timezone:
    name: Asia/Tehran
