
- name: Add yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  register: add_repository_key
  ignore_errors: True

- name: Add yarn repository
  apt_repository:
    repo: "{{ yarn_repository }}"
    state: present
    update_cache: yes

- name: Install yarn
  apt:
    name: yarn
    state: "present"
